### ISSUE TITLE
How about adding presentation😆

### ISSUE THREAD

**Issue by Shianiiiu** [filipeisho/pronounce#2]
I find it doesn't work.....and i have no idea how to solve it😫

**Comment by tryhardfifi** [comment]
Sorry to hear that! Are you using chrome or firefox? 

Also, can I ask you how you found this repo? Yesterday it had 50 stars and it now it has 100 stars and I can't seem to find where all of this traffic is coming from.

**Comment by ycrao** [comment]
@filipeisho by ruanyf/weekly https://github.com/ruanyf/weekly/blob/master/docs/issue-138.md

**Comment by hqzh** [comment]
![1](https://user-images.githubusercontent.com/26128706/102682455-8692c480-4204-11eb-8891-d20ceb3ef4de.png)
![2](https://user-images.githubusercontent.com/26128706/102682457-8bf00f00-4204-11eb-82fa-e4c3be6affee.png)

**Comment by hqzh** [comment]
```js
{

  "manifest_version": 2,
  "name": "Double-click pronounce",
  "version": "2.4",

  "description": "Never doubt how to pronounce a word. Better your spoken languages!",

  "icons": {
    "48": "icons/border-48.png"
  },

"background": {
 "persistent": false,
 "scripts": [
     "browser-polyfill.js"
   ]
 },
 "content_scripts": [
    {
      "matches": ["<all_urls>"],
      "js": ["browser-polyfill.js","pronounce.js"]
    }
  ],

 "options_ui": {
    "page": "options.html"
  },

  "permissions": ["storage", "management"],

  "browser_specific_settings": {
    "gecko": {
      "id": "{f8716d82-2c5c-430d-b783-5473310342cf}"
    }
  },
  "browser_action": {
    "default_icon": {
      "32": "icons/border-48.png"
    },

    "default_title": "Pronounce",
    "default_popup": "options.html"
    }
  


}
```

**Comment by tryhardfifi** [comment]
Hey @Shianiiiu I can't help you if you don't tell me what you are using!
Thanks @ycrao for the information, it was blowing my mind!
And @hqzh, those errors don't mean anything, it's just that I am reusing code from the firefox extension and some of the settings are unrecognised by chrome, it will be fixed in the next release!

**Comment by hqzh** [comment]
but in my here not work,why not push chrome store

**Comment by Shianiiiu** [comment]
@filipeisho Sorry!!! i forgot this 😫 I'm longing to use it in chrome. Tnx agian for your notification!!

**Comment by tryhardfifi** [comment]
I will push it to the chrome store and hopefully everything will work!

**Comment by tryhardfifi** [comment]
Hey! double-click pronounce is now on the chrome store! You can download it [here](https://chrome.google.com/webstore/detail/double-click-pronounce/pohphjaomaaadphonldcdmfflfjhnlgf?hl=en)

**Comment by Shianiiiu** [comment]
> Hey! double-click pronounce is now on the chrome store! You can download it [here](https://chrome.google.com/webstore/detail/double-click-pronounce/pohphjaomaaadphonldcdmfflfjhnlgf?hl=en)

Get it!!!
